---
- name: Install postgres
  become: true
  become_user: root
  apt:
    name:
      - postgresql
      - postgresql-10-postgis-2.4
      - postgresql-client-10
      - postgresql-contrib
      - postgresql-server-dev-all
      - python3-psycopg2
    state: present
    update-cache: yes
    cache_valid_time: 43200

- name: Optimize Postgres for DB import
  lineinfile:
    dest: /etc/postgresql/10/main/postgresql.conf
    line: "{{ item }}"
    state: present
  with_items:
    - "work_mem = 32MB"
    - "shared_buffers = 4GB"
    - "maintenance_work_mem = 2GB"
    - "full_page_writes = off"
    - "autovacuum = off"
    - "wal_buffers = -1"
  when: packer is defined

- name: Remove write heavy Postgres config
  lineinfile:
    dest: /etc/postgresql/10/main/postgresql.conf
    line: "{{ item }}"
    state: absent
  with_items:
    - "work_mem = 32MB"
    - "shared_buffers = 4GB"
    - "maintenance_work_mem = 2GB"
    - "full_page_writes = off"
    - "autovacuum = off"
    - "wal_buffers = -1"
  when: not packer

- name: Add read heavy Postgres config
  lineinfile:
    dest: /etc/postgresql/10/main/postgresql.conf
    line: "{{ item }}"
    state: present
  with_items:
    - "work_mem = 100MB"
    - "shared_buffers = 512MB"
    - "effective_cache_size = 1024MB"
    - "checkpoint_segment = 32"
    - "checkpoint_completion_target = 0.9"
    - "default_statistics_target = 1000"
    - "maintenance_work_mem = 1GB"
  when: not packer


- name: Install postgres_hba configuration file.
  template: src=files/conf/pg_hba.conf dest=/etc/postgresql/10/main/pg_hba.conf
  notify: restart postgres

- name: restart postgres
  service: name=postgresql state=restarted

- name: Create user.
  postgresql_user:
    name: "{{project_name}}"
    role_attr_flags: "CREATEDB,SUPERUSER"

- name: Create database.
  postgresql_db:
    name: "{{project_name}}"
