---
- name: Install postgres
  become: true
  become_user: root
  apt:
    name:
      - postgresql
      - postgresql-9.5-postgis-2.2
      - postgresql-client-9.5
      - postgresql-contrib-9.5
      - postgresql-server-dev-all
      - python-psycopg2
    state: present
    update-cache: yes
    cache_valid_time: 43200

- name: Optimize Postgres for DB import
  template: src=files/conf/pg_write_heavy.conf dest=/etc/postgresql/9.5/main/postgresql.conf
  when: packer is defined

- name: Optimize Postgres for reads
  template: src=files/conf/pg_read_heavy.conf dest=/etc/postgresql/9.5/main/postgresql.conf
  when: not packer

- name: Install postgres_hba configuration file.
  template: src=files/conf/pg_hba.conf dest=/etc/postgresql/9.5/main/pg_hba.conf
  notify: restart postgres

- name: restart postgres
  service: name=postgresql state=restarted

- name: Create user.
  postgresql_user:
    name: "{{project_name}}"
    role_attr_flags: "CREATEDB,SUPERUSER"

- name: Create database.
  postgresql_db:
    name: "{{project_name}}"
