---
- hosts: servers
  vars_files:
    - vars.yml
    # We want the vault to be loaded conditionally, so we do if via the
    # `--extra-args` command line flag
    # - @vault.yml
  gather_facts: true
  become: true
  become_user: "{{ project_name }}"

  tasks:

  - name: Import Councils
    shell: "{{ project_root }}/env/bin/python {{ project_root }}/code/manage.py import_councils -u {{ alt_boundaries_url }}"

  - name: Set ONSPD tmp path
    set_fact:
      onspd_tmp_path: '/tmp/onspd'

  - name: Create the ONSPD tmp dir
    file: state=directory path={{ onspd_tmp_path }}

  - name: Download ONSPD
    get_url:
      url: "{{ onspd_url }}"
      dest: "{{ onspd_tmp_path }}"

  - name: Unzip ONSPD
    shell: "unzip \\*.zip"
    args:
      chdir: "{{ onspd_tmp_path }}"

  - name: Import ONSPD
    shell: "{{ project_root }}/env/bin/python {{ project_root }}/code/manage.py import_onspd \"{{ onspd_tmp_path }}/Data\""

  - name: Delete ONSPD tmp files
    file:
      state: absent
      path: "{{ onspd_tmp_path }}"

  - name: Set addressbase tmp path
    set_fact:
      addressbase_tmp_path: '/tmp/addressbase'

  - name: Set ONSUD tmp path
    set_fact:
      onsud_tmp_path: '/tmp/onsud'

  - name: Create the addressbase tmp dir
    file: state=directory path={{ addressbase_tmp_path }}

  - name: Download addressbase from S3
    command: "aws s3 --region={{ build_region }} cp s3://pollingstations-packer-assets/addressbase/{{ addressbase_file_name }} {{ addressbase_tmp_path }}/addressbase_cleaned.csv"

  - name: Import addresses
    shell: "{{ project_root }}/env/bin/python {{ project_root }}/code/manage.py import_cleaned_addresses {{ addressbase_tmp_path }}"

  - name: Delete addressbase tmp files
    file:
      state: absent
      path: "{{ addressbase_tmp_path }}"

  - name: Create the ONSUD tmp dir
    file: state=directory path={{ onsud_tmp_path }}

  - name: Download ONSUD
    get_url:
      url: "{{ onsud_url }}"
      dest: "{{ onsud_tmp_path }}"

  - name: Unzip ONSUD
    shell: "unzip \\*.zip"
    args:
      chdir: "{{ onsud_tmp_path }}"

  - name: Import ONSUD
    shell: "{{ project_root }}/env/bin/python {{ project_root }}/code/manage.py import_onsud {{ onsud_tmp_path }}/Data"

  - name: Create postcode blacklist
    shell: "{{ project_root }}/env/bin/python {{ project_root }}/code/manage.py create_blacklist"

  - name: Delete ONSUD tmp files
    file:
      state: absent
      path: "{{ onsud_tmp_path }}"
