---
- hosts: all
  vars_files:
    - vars.yml
  gather_facts: true
  become: true
  become_user: "root"
  tasks:
  - name: Install output on error
    template:
      src: files/scripts/output-on-error
      dest: /usr/local/bin/output-on-error
      mode: 0777
    become_user: root

  - cronvar:
      name: MAILTO
      value: "{{ cron_email }}"
      user: "every_election"

  - name: Schedule sync local EE data from source
    cron:
      name: "Sync local EE data from source"
      minute: 0
      hour: 4
      job: "/var/www/every_election/env/bin/python /var/www/every_election/code/manage.py sync_elections"
      user: "every_election"
