---
- hosts: servers
  vars_files:
    - vars.yml
    # We want the vault to be loaded conditionally, so we do if via the
    # `--extra-args` command line flag
    # - @vault.yml
  gather_facts: true
  become: true
  become_user: "{{ project_name }}"

  tasks:

  - name: Import Councils
    shell: "{{ project_root }}/env/bin/python {{ project_root }}/code/manage.py import_councils -u {{ alt_boundaries_url }}"
    args:
      chdir: "{{ project_root }}/code/"

  - name: Create private_data_path
    file: state=directory path={{ private_data_path }}

  - name: Sync S3 bucket
    shell: "aws s3 sync s3://pollingstations-data/ {{ private_data_path }}"

  - name: Import data
    shell: "{{ project_root }}/env/bin/python {{ project_root }}/code/manage.py import -e '{{ election_regex }}' -r --multiprocessing"
    args:
       executable: /bin/bash
       chdir: "{{ project_root }}"

  - name: Delete private_data_path
    file: state=absent path={{ private_data_path }}
