#!/bin/bash -e
# Run with:
# ./packer database
# ./packer server
type="${1?Usage $0 '[addressbase|imported-db|server]'}"
shift;
/usr/bin/env packer build -var-file=packer-vars.json -var-file=packer-user-vars.json -only="${type}" "$@" packer.json
