---
- hosts: all
  vars_files:
    - "../vars.yml"
  #vars:
  #  image_id: {stdout: "TODO"}
  gather_facts: true
  become: true
  become_user: "{{ project_name }}"

  tasks:
  - name: Upload configuration.
    template: src="../webapp_settings/{{ nickname }}.py" dest="{{ project_root }}/code/{{ app_name }}/settings/local.py"
    notify:
      - restart web frontend

  handlers:
    - import_tasks: "../handlers.yml"
