---
- hosts: all
  vars_files:
    - "../vars.yml"
  gather_facts: true
  become: true
  become_user: "{{ project_name }}"

  tasks:

  - name: Pull sources from the repository.
    git:
      repo: "{{ project_repo }}"
      dest: "{{ project_root }}/code/"
      version: "{{ branch }}"
      accept_hostkey: true
      force: yes
    notify:
      - restart web frontend

  - name: Import Councils on instances
    shell: "{{ project_root }}/env/bin/python {{ project_root }}/code/manage.py import_councils -u {{ alt_boundaries_url }}"
    args:
      chdir: "{{ project_root }}/code/"

  - name: Import Councils on logger database
    shell: "{{ project_root }}/env/bin/python {{ project_root }}/code/manage.py import_councils -u {{ alt_boundaries_url }} --database logger"
    args:
      chdir: "{{ project_root }}/code/"
    run_once: True


  handlers:
    - import_tasks: "../handlers.yml"
